server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
    openfeign:
      client:
        config:
          default:
            connect-timeout: 20000
            read-timeout: 20000
            logger-level: full
          cloud-payment-service:
            connect-timeout: 30000
            read-timeout: 30000
      compression:
        request:
          enabled: true
          mime-types: text/xml;application/json
          min-request-size: 2048
        response:
          enabled: true
      httpclient:
        hc5:
          enabled: true
      circuitbreaker:
        enabled: true
        group:
          enabled: true
logging:
  level:
    com:
      sfuhome:
        api:
          PayFeignApi: debug
resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 6
        minimumNumberOfCalls: 6
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        recordExceptions:
         - java.lang.Exception
    instances:
      cloud-payment-services:
        baseConfig: default
